# Generated by Django 3.2.12 on 2022-05-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='readers',
        ),
        migrations.AddField(
            model_name='profile',
            name='reading',
            field=models.ManyToManyField(blank=True, null=True, related_name='reading', to=settings.AUTH_USER_MODEL),
        ),
    ]
