# Generated by Django 3.2.12 on 2022-05-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220512_2016'),
        ('tweets', '0003_auto_20220515_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedtweet',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='likedtweet',
            name='tweet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
