# Generated by Django 3.2.12 on 2022-05-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_delete_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='liked',
        ),
    ]
