# Generated by Django 3.2.12 on 2022-05-23 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20220523_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='liked',
        ),
    ]
