# Generated by Django 3.2.12 on 2022-05-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_remove_tweet_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='responses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
