# Generated by Django 3.2.12 on 2022-05-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_tweet_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='responses',
        ),
    ]
