# Generated by Django 3.2.12 on 2022-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0014_remove_tweet_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
