# Generated by Django 3.2.12 on 2022-05-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0015_tweet_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
        migrations.AddField(
            model_name='tweet',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
