# Generated by Django 3.2.5 on 2022-06-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_username'),
        ('tweets', '0017_retweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tweets/attached_images/')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senders_responses', to='profiles.profile')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='tweets.tweet')),
            ],
        ),
    ]
