# Generated by Django 3.2.5 on 2022-06-03 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0019_rename_sender_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedtweet',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.response'),
        ),
        migrations.AlterField(
            model_name='likedtweet',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
