# Generated by Django 3.2.5 on 2022-06-03 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0020_auto_20220603_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedtweet',
            name='response',
        ),
        migrations.AlterField(
            model_name='likedtweet',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
