# Generated by Django 3.2.5 on 2022-06-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0022_auto_20220603_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.conversation'),
        ),
    ]
