# Generated by Django 3.2.5 on 2022-06-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0023_alter_tweet_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.conversation'),
        ),
    ]
