# Generated by Django 3.2.5 on 2022-06-03 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0024_alter_tweet_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.conversation'),
        ),
    ]
