# Generated by Django 3.2.5 on 2022-06-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0027_alter_tweet_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
