# Generated by Django 3.2.5 on 2022-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0028_alter_tweet_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='as_response',
            field=models.BooleanField(default=False),
        ),
    ]
